[versions]
agp = "8.7.0"
chiliphotopicker = "0.3.1"
eazegraph = "1.2.2"
glide = "4.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
library = "2.4.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.1.4"
legacySupportV4 = "1.0.0"
recyclerview = "1.3.2"
kotlin = '2.0.21'
coreKtx = "1.13.1"
snaptablayout = "7a9ec577ab"
tagSphere = "1.0.0"
tensorflowLite = "2.10.0"
tensorflowLiteTaskVision = "0.3.1"

[libraries]
chiliphotopicker = { module = "com.github.ChiliLabs:ChiliPhotoPicker", version.ref = "chiliphotopicker" }
eazegraph = { module = "com.github.blackfizz:eazegraph", version.ref = "eazegraph" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
library = { module = "com.nineoldandroids:library", version.ref = "library" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
snaptablayout = { module = "com.github.nirukk52:SnapTabLayout", version.ref = "snaptablayout" }
tag-sphere = { module = "com.github.magic-goop:tag-sphere", version.ref = "tagSphere" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
tensorflow-lite-gpu = { module = "org.tensorflow:tensorflow-lite-gpu", version.ref = "tensorflowLite" }
tensorflow-lite-support = { module = "org.tensorflow:tensorflow-lite-support", version.ref = "tensorflowLiteTaskVision" }
tensorflow-lite-task-vision = { module = "org.tensorflow:tensorflow-lite-task-vision", version.ref = "tensorflowLiteTaskVision" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

